### ISSUE TITLE
How to add aar files

### ISSUE THREAD

**Issue by nitheshbafna** [profusion/android-sdk-addon-example#3]
Hi, it would be nice if you can explain if it's possible to add .aar files as well?

**Comment by oliveirarleo** [comment]
Have you tried adding [using gradle](https://nphau.medium.com/android-how-to-include-an-external-aar-file-using-gradle-ddc4b2b8fad0)?

**Comment by nitheshbafna** [comment]
Hi, Thanks for the response Currently the above example shows how to add a java library to sdk_addon. I have an android library in my soong build system. and can I add it as part of the SDK addon?
For example: 
The HelloWorld module is a java library(jar) so you used java_sdk_library. but what if it's an android library(aar)?

**Comment by oliveirarleo** [comment]
Looks like you can use `android_library_import` on your bp file. Here it's an example
```yaml
android_library_import {
    name: "your-lib-name",
    aars: ["your-lib-file-name.aar"],
    sdk_version: "current",
    min_sdk_version: "28", // optional
}
```

For more info, please look into the [documentation](https://storage.googleapis.com/android-build/builds/aosp-build-tools-linux-linux/7967930/2acd0eb7c7ba62b80f8847c32a5938c925117d7f797dc13a7cbd2fab77293891/java.html?GoogleAccessId=gcs-sign@android-builds-project.google.com.iam.gserviceaccount.com&Expires=1645193128&Signature=HnA5ZEf44rQRqKlS7dYToiiJ/KVb0PMO1raUDCM5/oZBnu44cBDBXIq2jlE7ZiyJMvZKHWFl6bnf0Fw%2B794uFO1HM8dkDbyCBE5dXeJ77uuVKlS/Nx27qDdFkglDSTFUcIKnI/9VdGyTr9D9V9D3zcYyEAvPXzso1CKQbQNOjTnboSVXAIwXnAIyQbChZUmdVUz%2BY6Pv8vprwiaE5Q93ERY4Ppvqz7rIx4CvtTlhcKeAzGiEDsilxUErYkdyADkVlVY1reJ/5IJiByYfD5rTAD1dqFJ28eCkOqnzBTyh4d1g5KegGdmQLkml5IxSpHUUQzG%2B/sJktr02Vt5KisMnMg%3D%3D#android_library_import)

**Comment by nitheshbafna** [comment]
Hi,
The above code "android_library_import " is to add the aar file but i am asking for something similar to "java_sd_library" which builds the existing java code to java SDK library to SDK.
