### ISSUE TITLE
Update the tutorial to the latest android version

### ISSUE THREAD

**Issue by g7fernandes** [profusion/android-sdk-addon-example#8]
That's it. Details discussed internally at ProFUSION

**Comment by khvMX** [comment]
Hi there! Thanks for the efforts I have been through that (migration to Android 14) recently so if you face any issues, I may be able to help.
Also, please consider joining https://aosp-devs.org and its discord server, if you would like more people to contribute :)

**Comment by MaironLucas** [comment]
Oh, hi @khvMX. Maybe you can help me. Were you able to migrate and compile the sdk-addon?
I'am facing some troubles running the `make sdk_addon` command here. Looks like the `java_sdk_library` is trying to find the modules `helloworldservice.api.public.latest`, `helloworldservice-removed.api.public.latest`, `helloworldservice.api.system.latest` and `helloworldservice-removed.api.system.latest`, but this modules aren't being generated (or I don't how to link then in the Android.bp). Have you faced something like that?

**Comment by khvMX** [comment]
It should also spit out a command to generate missing api interfaces. I did not need any versioning, so I am ok with `unsafe_ignore_missing_latest_api: true,` in `java_sdk_library` target. Strangely enough it still made me generate a bunch of empty files in `api/` directory.

**Comment by MaironLucas** [comment]
@khvMX did you have an idea of how can I fix this error?
```
build/make/core/tasks/sdk-addon.mk:83: error: overriding commands for target `out/host/linux-x86/obj/SDK_ADDON/profusion_sdk_addon_intermediates/profusion_sdk_addon--img/', previously defined at build/make/core/tasks/sdk-addon.mk:83
18:35:47 ckati failed with: exit status 1
```

**Comment by MaironLucas** [comment]
@khvMX  I thinked that "call inherit-product" can be trying to create the img twice, but I can't find where this is happening. Honestly, this is my first time working with AOSP and SDK-Addon, so I don't understand exactly how the things work and connect yet.
I already tried to remove the `$(call inherit-product, device/profusion/profusion_sdk_addon/profusion_sdk_addon.mk)` line from aosp_x86_64.mk and the `$(call inherit-product, device/profusion/common/profusion-packages.mk)` line from mainline_system.mk. But this way compilation failed on the begining.
I created a [draft](https://github.com/profusion/android-sdk-addon-example/pull/9) for the branch I'm working on, can you take a quick look and see if you spot something that I am doing wrong?
